### ISSUE TITLE
ROSbot 2 unable to pull docker

### ISSUE THREAD

**Issue by autonomousTurtle** [husarion/rosbot-docker#19]
Hello! 

When running the commands from the setup documentation [here](https://husarion.com/tutorials/howtostart/rosbot---quick-start/), I am unable to pull docker images using 

`docker compose -f /home/husarion/compose.minimal.ros.yaml pull`

I receive the error unknown shorthand flag: 'f' in -f

My docker-compose version is 1.17.1-2. ROS version is Melodic. 

_Update: After reading docker documentation, I attempted to pull using the command:_ 

`COMPOSE_FILE=/home/husarion/compose.minimal.ros.yaml docker-compose pull`

**OUTPUT:** 

ERROR: The Compose file '/home/husarion/compose.minimal.ros.yaml' is invalid because:
Unsupported config option for services: 'rosbot'

**Comment by delihus** [comment]
Hi @autonomousTurtle!
Here is the correct way to install docker https://docs.docker.com/desktop/install/ubuntu/.

If the issues persist, kindly request their reopening.
Best regards,
JD
