### ISSUE TITLE
Commit 91b29b61aff7aab87a440217a096a6900d49e6ac deletes compose files

### ISSUE THREAD

**Issue by oldtopos** [husarion/rosbot-docker#25]
The commit a few days ago deletes a set of very useful docker compose files; I suggest they be restored.  I recently brought up a rosbot after a RPi4 swap and it would have takena lot longer without the compose files

**Comment by delihus** [comment]
Hi @oldtopos!
Feel free to fork the repository and restore the files you need.
You can also check our [telepresence](https://github.com/husarion/rosbot-telepresence), [mapping](https://github.com/husarion/rosbot-mapping) and [navigation](https://github.com/husarion/rosbot-navigation) demos.

Best regards,
JD
